# Flutter Analysis Options
# Enforces Hiroshi-level performance standards

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    # Error handling
    - avoid_catching_errors
    - avoid_catches_without_on_clauses
    
    # Performance
    - prefer_final_locals
    - avoid_unused_constructor_parameters
    
    # Style
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    
    # Best practices
    - prefer_single_quotes
    - require_trailing_commas
    - unnecessary_brace_in_string_interps
